# Generated by Django 3.0.5 on 2020-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201103_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'started'), ('lost', 'lost'), ('won', 'won')], default='started', max_length=10, verbose_name='status'),
        ),
    ]
