# Generated by Django 3.1.3 on 2020-11-02 22:49

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import games.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('finished_time', models.DateTimeField(blank=True, null=True, verbose_name='finished time')),
                ('secret', models.CharField(default=games.models.get_secret, max_length=12, unique=True)),
                ('status', models.CharField(blank=True, choices=[('started', 'started'), ('lost', 'lost'), ('won', 'won')], max_length=10, verbose_name='status')),
                ('rows', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='rows')),
                ('cols', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='cols')),
                ('mines', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9900)], verbose_name='mines')),
                ('field', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=100), size=100)),
                ('game_board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=100), size=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
    ]
