# Generated by Django 3.0.5 on 2020-11-03 14:48

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201102_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cols',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)], verbose_name='cols'),
        ),
        migrations.AlterField(
            model_name='game',
            name='field_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', ''), ('m', 'm')], max_length=1), size=25), size=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', ''), ('?', '?'), ('f', 'f'), ('x', 'x')], max_length=1), size=25), size=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='mines',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(312)], verbose_name='mines'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rows',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)], verbose_name='rows'),
        ),
    ]
